---
title: "Day 20 - 10/04/2024"
format: html
editor: visual
---

## Announcements  

- [Mid-semester feedback survey](https://forms.gle/5W3AWhzrEtoysn3P6) (please and thank you!)
- 

## Model selection demo  

```{r message=FALSE, warning=FALSE}
library(tidyverse)
```

### Load the data:  
```{r warning=FALSE}
dd_yield <- readxl::read_xlsx("data/8.Yield_Plant_Measurements.xlsx", sheet = 2) %>%
  filter(Year == 2014, 
         State == "IA", 
         Site == "Ames") %>% 
  mutate(across(VT_TissN:R4N, ~ as.numeric(.)))
dd_soil <- readxl::read_xlsx("data/1.Site_Characterization.xlsx", sheet = 2) %>% 
  filter(Year == 2014, 
         State == "IA", 
         Site == "Ames", 
         Horizon == "Ap") %>% 
  mutate(Block = as.numeric(Block), 
         across(Clay:WC, ~as.numeric(.)))
dd_N <- readxl::read_xlsx("data/4.SoilN.xlsx", sheet = 2) %>% 
  filter(Year == 2014, 
         State == "IA", 
         Site == "Ames") %>% 
  mutate(across(c(Plot_ID, N_Trt, Plant_N, Side_N, Plant_N_SI, Side_N_SI), ~as.numeric(.)))
dd_N
```

```{r warning=FALSE}
dd_yield <- readxl::read_xlsx("data/8.Yield_Plant_Measurements.xlsx", sheet = 2) %>%
  filter(Year == 2014, 
         State == "IA", 
         Site == "MasonCity") %>% 
  mutate(across(VT_TissN:R4N, ~ as.numeric(.)))
dd_soil <- readxl::read_xlsx("data/1.Site_Characterization.xlsx", sheet = 2) %>% 
  filter(Year == 2014, 
         State == "IA", 
         Site == "MasonCity", 
         Horizon == "Ap") %>% 
  mutate(Block = as.numeric(Block), 
         across(Clay:WC, ~as.numeric(.)))
dd_N <- readxl::read_xlsx("data/4.SoilN.xlsx", sheet = 2) %>% 
  filter(Year == 2014, 
         State == "IA", 
         Site == "MasonCity") %>% 
  mutate(across(c(Plot_ID, N_Trt, Plant_N, Side_N, Plant_N_SI, Side_N_SI), ~as.numeric(.)))
dd_N
```

```{r}
dd_complete <- dd_yield %>% 
  left_join(dd_soil) %>% 
  left_join(dd_N)

dd_complete <- dd_complete %>% 
  mutate(gyield_14 = GYdry/.94, 
         N_total = Plant_N_SI + Side_N_SI)
```

```{r}
dd_complete %>% 
  ggplot(aes(N_total, GYdry))+
  geom_point()
```

```{r}
m1 <- lm(GYdry ~ N_total + I(N_total^2), data = dd_complete)
m2 <- lm(GYdry ~ N_total + I(N_total^2) + Block , data = dd_complete)
m3 <- lm(GYdry ~ N_total + I(N_total^2) + Block + TOC, data = dd_complete)
m4 <- lm(GYdry ~ N_total + I(N_total^2) + Block + TOC + Clay, data = dd_complete)   
m5 <- lm(GYdry ~ N_total + I(N_total^2) + Block + TOC + Clay + Sand, data = dd_complete)
m6 <- lm(GYdry ~ N_total + I(N_total^2) + Block + TOC + Clay + Sand + Silt, data = dd_complete)
```

```{r}
summary(m1)
summary(m5)
summary(m6)
```

```{r}
metrics <- data.frame(model = c("N_total + I(N_total^2)",
                                "N_total + I(N_total^2) + Block",
                                "N_total + I(N_total^2) + Block + Plot_ID", 
                                "N_total + I(N_total^2) + Block + Plot_ID + Clay", 
                                "N_total + I(N_total^2) + Block + Plot_ID + Clay + Sand", 
                                "N_total + I(N_total^2) + Block + Plot_ID + Clay + Sand + Silt"),
                      R2 = c(summary(m1)$r.squared, summary(m2)$r.squared, summary(m3)$r.squared,
                             summary(m4)$r.squared, summary(m5)$r.squared, summary(m6)$r.squared),
                      R2_adj = c(summary(m1)$adj.r.squared, summary(m2)$adj.r.squared, summary(m3)$adj.r.squared,
                                 summary(m4)$adj.r.squared, summary(m5)$adj.r.squared, summary(m6)$adj.r.squared),
                      AIC = AIC(m1, m2, m3, m4, m5, m6)$AIC,
                      BIC = BIC(m1, m2, m3, m4, m5, m6)$BIC) 

knitr::kable(metrics, format = "html")
```

```{r}
data_plot <- expand.grid(N_total = seq(0, 300, by = 5), 
                         Block = 1:4)
data_plot <- data_plot %>% bind_cols(predict(m2, newdata = data_plot, interval = "confidence"))
```

```{r}
dd_complete %>% 
  ggplot(aes(N_total, GYdry))+
  theme_classic()+
  geom_ribbon(aes(y = fit, ymin = lwr, ymax = upr, group = Block), data = data_plot, alpha = .15)+
  geom_line(aes(y = fit, group = Block), data = data_plot)+
  geom_point()
```

::: {.alert .alert-info}
<strong>Important concepts</strong>  

- Collinearity   
- Aim for simple models  

:::



